spring:
  application:
    name: search
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://bj-cdb-chl0kfgo.sql.tencentcdb.com:29610/sphinx_dev?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: shangxun_dev
    password: qFTJvKh4RB4FDPsT1Hr0
  # Elasticsearch 配置
  elasticsearch:
    uris: http://localhost:9200
    username: root
    password: 123456
server:
  port: 8757
#mybatis-plus:
#  configuration:
#    map-underscore-to-camel-case: false
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  global-config:
#    db-config:
#      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
#      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
#      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
